/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projekt_ks;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Karol
 */
public class JFrameAppUser extends javax.swing.JFrame {

    ArrayList<Employee> baza_prac = new ArrayList<>();
     ArrayList<Team> array_team = new ArrayList<>();
     ArrayList<Team_Employee> array_team_employee = new ArrayList<>();
     ArrayList<Project> array_project = new ArrayList<>();
   // List<String> listaPESELI = new ArrayList<String>();
    Employee dodaj;
    Team add_team;
    Project add_project;
    Team_Employee add_team_employee;
    Connection c = null;
    Statement stmt = null;
    String sorting = null;   
    /**
     * Creates new form JFrameAppUser
     */
    public JFrameAppUser() {
        initComponents();
    }
    
    public JFrameAppUser(int nr_pracownika) {
        initComponents();
        //String numberAsString = Integer.toString(number);
        jLabel1.setText(Integer.toString(nr_pracownika));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("jLabel1");

        jLabel2.setText("User #");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "login", "email", "Imie", "Nazwisko"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTextField1.setText("Login");

        jTextField2.setText("Email");

        jTextField3.setText("Imie");

        jTextField4.setText("Nazwisko");

        jButton1.setText("Odśwież");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Popraw dane");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jTextField5.setText("jTextField5");
        jTextField5.setVisible(false);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Team ID", "Imie", "Nazwisko", "Nazwa", "leader ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jButton3.setText("Odśwież");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jLabel3.setText("Dane użytkownika");

        jLabel4.setText("Moje zespoły");

        jLabel5.setText("Moje projekty");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nr", "Nazwa", "Stan", "Rozpoczęcie", "Zakończenie", "Team", "Opis"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jButton4.setText("Odśwież");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(459, Short.MAX_VALUE)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(190, 190, 190)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton4))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jButton2))))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(662, 662, 662)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
        
        
        String Sterownik = "com.mysql.jdbc.Driver";
        try {
            Class.forName(Sterownik);
            String url = "jdbc:mysql://localhost/database";
            String user = "root";
            String pass = "";
            //Connection conn = DriverManager.getConnection(URL, USER, PASS);
            c = DriverManager.getConnection(url, user, pass);            
            c.setAutoCommit(false);

            clean_table();
        

            stmt = c.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM employee where employee_ID="+jLabel1.getText()+" ;");

            while (rs.next()) {
                int id = rs.getInt("employee_ID");
                String login = rs.getString("login");
                String email = rs.getString("email");
                String imie = rs.getString("first_Name");
                String nazwisko = rs.getString("last_Name");
                String position = rs.getString("position");
                String password = rs.getString("password");
            
                dodaj = new Employee(id, login, email, imie, nazwisko, password, position);
                baza_prac.add(dodaj);
               // listaPESELI.add(dodaj.getPESEL());

            }
            rs.close();
            stmt.close();
            c.close();
            wyswietlWiersz();
            JOptionPane.showMessageDialog(null, "Baza załadowana pomyślnie!");
        } catch (Exception e) {
            System.err.println(e.getClass().getName() + ": " + e.getMessage());
            System.exit(0);
        }
        
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        
        
         
          String Sterownik = "com.mysql.jdbc.Driver";
         
        try {
            Class.forName(Sterownik);
            String url = "jdbc:mysql://localhost/database";
            String user = "root";
            String pass = "";
            //Connection conn = DriverManager.getConnection(URL, USER, PASS);
            c = DriverManager.getConnection(url, user, pass);            
            c.setAutoCommit(false);

            clean_table2();
    

            stmt = c.createStatement();
// select employee.first_Name, employee.last_Name, team.name from employee, team, team_employee WHERE employee.employee_ID = team_employee.employee_ID and team.team_ID = team_employee.team_ID
            ResultSet rs = stmt.executeQuery("select employee.first_Name, employee.last_Name, team.name, team.team_ID, employee.employee_ID, team.leader_ID from employee, team, team_employee WHERE employee.employee_ID = team_employee.employee_ID and team.team_ID = team_employee.team_ID AND employee.employee_ID="+jLabel1.getText()+" ;");

            while (rs.next()) {
                int team_id = rs.getInt("team_ID");
                 int employee_id = rs.getInt("employee_ID");
                  int leader_id = rs.getInt("leader_ID");
                String team_name = rs.getString("name");
               String nazwisko = rs.getString("last_Name");
               String imie = rs.getString("first_Name");
               // Team_Employee(int employee_ID, String first_Name, String last_Name, int team_id, String name, int leader_id)
                add_team_employee = new Team_Employee(employee_id,imie, nazwisko,team_id, team_name,leader_id);
               array_team_employee.add(add_team_employee);
               // listaPESELI.add(dodaj.getPESEL());

            }
            rs.close();
            stmt.close();
            c.close();
            wyswietlWiersz2();
            JOptionPane.showMessageDialog(null, "Baza załadowana pomyślnie!");
        } catch (Exception e) {
            System.err.println(e.getClass().getName() + ": " + e.getMessage());
            System.exit(0);
        }
        
        
        
        
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
//Select p.project_ID, p.name, p.state, p.start, p.finish, p.team_ID, p.description FROM project p, team_employee te ,team t, employee e where e.employee_ID = 1 AND te.team_ID = p.team_ID AND e.employee_ID = te.employee_ID        
        
          String Sterownik = "com.mysql.jdbc.Driver";
         
        try {
            Class.forName(Sterownik);
            String url = "jdbc:mysql://localhost/database";
            String user = "root";
            String pass = "";
            //Connection conn = DriverManager.getConnection(URL, USER, PASS);
            c = DriverManager.getConnection(url, user, pass);            
            c.setAutoCommit(false);

            clean_table3();
    

            stmt = c.createStatement();
            ResultSet rs = stmt.executeQuery("Select p.project_ID, p.name, p.state, p.start, p.finish, p.team_ID, p.description FROM project p, team_employee te ,team t, employee e where e.employee_ID = "+jLabel1.getText()+" AND te.team_ID = p.team_ID AND e.employee_ID = te.employee_ID GROUP BY p.name ;");

            while (rs.next()) {
                int project_id = rs.getInt("project_ID");
                String name = rs.getString("name");
               String state = rs.getString("state");
             //  Date start = rs.getDate(start);
             Date start = rs.getObject("start", Date.class);
              Date finish = rs.getObject("finish", Date.class);
              int team_id = rs.getInt("team_id");
               String description = rs.getString("description");
                add_project = new Project(project_id, name, state, start, finish, team_id, description);
               // System.out.println(add_project.getDescription());
               array_project.add(add_project);
              

            }
            rs.close();
            stmt.close();
            c.close();
            wyswietlWiersz3();
            JOptionPane.showMessageDialog(null, "Baza załadowana pomyślnie!");
        } catch (Exception e) {
            System.err.println(e.getClass().getName() + ": " + e.getMessage());
            System.exit(0);
        }
        
    }//GEN-LAST:event_jButton4MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
                // TODO add your handling code here: pobranie wiersza
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        int selectedRowIndex = jTable1.getSelectedRow();
        // set the selected row data into jtextfields
        
      
        jTextField1.setText(model.getValueAt(selectedRowIndex, 0).toString());
        jTextField2.setText(model.getValueAt(selectedRowIndex, 1).toString());
        jTextField3.setText(model.getValueAt(selectedRowIndex, 2).toString());
        jTextField4.setText(model.getValueAt(selectedRowIndex, 3).toString());
       
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
          
                String login = jTextField1.getText();
                String email = jTextField2.getText();
                String imie = jTextField3.getText();
                String nazwisko = jTextField4.getText();
                String id = jLabel1.getText();
                //int id = Integer.parseInt(jTextField6.getText());
             
                
                
                  try {

            //Creating Connection Object
            Class.forName("com.mysql.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost/database", "root", "");
            connection.setAutoCommit(false);
            System.out.println("Opened database successfully");

            stmt = connection.createStatement();
            String sql = "UPDATE `employee` SET `first_Name`=?,`last_Name`=?,`login`=?,`email`=? WHERE employee_ID = ? ";
            PreparedStatement pst = connection.prepareStatement(sql);
            pst.setString(1, imie);
            pst.setString(2, nazwisko);
            pst.setString(3, login);
            pst.setString(4, email);
            pst.setString(5, id);
            pst.executeUpdate();

            // stmt.executeUpdate(sql);
            connection.commit();

            stmt.close();
            connection.close();
            JOptionPane.showMessageDialog(null, "Dane poprawione");
        } catch (Exception e1) {
            JOptionPane.showMessageDialog(null, "Błąd Edycji!");
            System.err.println(e1.getClass().getName() + ": " + e1.getMessage());
            e1.printStackTrace();
        }
        
        
        
        
    }//GEN-LAST:event_jButton2MouseClicked

    
     public void clean_table() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       
        model.setRowCount(0);
      
        jTable1.repaint();
       
        baza_prac.clear();
      
    }
         public void wyswietlWiersz() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
      
        model.setRowCount(0);
       
        Object rowData[] = new Object[7];
        for (int i = 0; i < baza_prac.size(); i++) {
            
           
            rowData[0] = baza_prac.get(i).getLogin();
            rowData[1] = baza_prac.get(i).getEmail();
            rowData[2] = baza_prac.get(i).getFirst_Name();
            rowData[3] = baza_prac.get(i).getLast_Name();
          
           
            model.addRow(rowData);

        }
           

    }
         
                      public void wyswietlWiersz2() {
        
        DefaultTableModel model2 = (DefaultTableModel) jTable2.getModel();
      
         model2.setRowCount(0);
    
            Object rowData4[] = new Object[7];
        for (int i = 0; i < array_team_employee.size(); i++) {
// Team_Employee(int employee_ID, String first_Name, String last_Name, int team_id, String name, int leader_id)
            rowData4[0] = array_team_employee.get(i).getTeam_id();
            rowData4[1] = array_team_employee.get(i).getFirst_Name();
            rowData4[2] = array_team_employee.get(i).getLast_Name(); 
            rowData4[3] = array_team_employee.get(i).getName();
            rowData4[4] = array_team_employee.get(i).getLeader_id();
                  
            
           
            model2.addRow(rowData4);

        }

    }
                       public void wyswietlWiersz3() {
        
        DefaultTableModel model3 = (DefaultTableModel) jTable3.getModel();
      
         model3.setRowCount(0);
    
            Object rowData3[] = new Object[7];
        for (int i = 0; i < array_project.size(); i++) {

            rowData3[0] = array_project.get(i).getProject_id();
            rowData3[1] = array_project.get(i).getName();
            rowData3[2] = array_project.get(i).getState();
            rowData3[3] = array_project.get(i).getStart();
            rowData3[4] = array_project.get(i).getFinish();
            rowData3[5] = array_project.get(i).getTeam_id();
            rowData3[6] = array_project.get(i).getDescription();
            
           
            model3.addRow(rowData3);

        }

    }
                        public void clean_table2() {
        
        DefaultTableModel model2 = (DefaultTableModel) jTable2.getModel();
      
        model2.setRowCount(0);
       
        jTable2.repaint();
    
        array_team_employee.clear();
    }
                         public void clean_table3() {
        
        DefaultTableModel model3 = (DefaultTableModel) jTable3.getModel();
      
        model3.setRowCount(0);
       
        jTable3.repaint();
    
        array_project.clear();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAppUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAppUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAppUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAppUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAppUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
